/**
 * ClipSheet.gs
 * Helpers for the "clips" sheet tab.
 *
 * Columns (1-based):
 *   A  video_url      — source video URL or reference
 *   B  video_title    — title entered by user
 *   C  clip_title     — short title generated by Groq
 *   D  start          — clip start timestamp e.g. "1:23" or "01:23:45"
 *   E  end            — clip end timestamp
 *   F  status         — 'pending' | 'generating' | 'ready' | 'error'
 *   G  drive_link     — Google Drive view link of generated clip
 *   H  drive_file_id  — Drive file ID of generated clip
 *   I  created_at     — ISO timestamp when row was created
 *   J  summary        — one-sentence summary from Groq
 *   K  error_msg      — error message if status = 'error'
 *   L  video_file_id  — Drive file ID of the SOURCE video (for shortclips flow)
 */

var CL_COL_VIDEO_URL    = 1;
var CL_COL_VIDEO_TITLE  = 2;
var CL_COL_CLIP_TITLE   = 3;
var CL_COL_START        = 4;
var CL_COL_END          = 5;
var CL_COL_STATUS       = 6;
var CL_COL_DRIVE_LINK   = 7;
var CL_COL_DRIVE_FILE   = 8;
var CL_COL_CREATED_AT   = 9;
var CL_COL_SUMMARY      = 10;
var CL_COL_ERROR_MSG    = 11;
var CL_COL_VIDEO_FILE_ID = 12;

// ============================================================
// Sheet bootstrap
// ============================================================

/**
 * Returns the clips sheet, creating it with headers if it doesn't exist.
 * @returns {GoogleAppsScript.Spreadsheet.Sheet}
 */
function getOrCreateClipSheet() {
  var ss    = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('clips');
  if (!sheet) {
    sheet = ss.insertSheet('clips');
    sheet.getRange(1, 1, 1, 11).setValues([[
      'video url', 'video title', 'clip title',
      'start', 'end', 'status',
      'drive link', 'drive file id', 'created at',
      'summary', 'error'
    ]]);
    sheet.setFrozenRows(1);
    sheet.setColumnWidth(CL_COL_VIDEO_URL,   280);
    sheet.setColumnWidth(CL_COL_VIDEO_TITLE, 200);
    sheet.setColumnWidth(CL_COL_CLIP_TITLE,  220);
    sheet.setColumnWidth(CL_COL_START,        80);
    sheet.setColumnWidth(CL_COL_END,          80);
    sheet.setColumnWidth(CL_COL_STATUS,       90);
    sheet.setColumnWidth(CL_COL_DRIVE_LINK,  260);
    sheet.setColumnWidth(CL_COL_SUMMARY,     300);
  }
  return sheet;
}

// ============================================================
// Write helpers
// ============================================================

/**
 * Appends one clip row with status = 'pending'.
 * @param {GoogleAppsScript.Spreadsheet.Sheet} sheet
 * @param {string} videoUrl
 * @param {string} videoTitle
 * @param {string} clipTitle
 * @param {string} start
 * @param {string} end
 * @param {string} summary
 * @returns {number}  1-based row index
 */
function addClipRow(sheet, videoUrl, videoTitle, clipTitle, start, end, summary, videoFileId) {
  var rowIndex = sheet.getLastRow() + 1;
  // Set text format BEFORE writing so Sheets cannot auto-convert timestamps
  sheet.getRange(rowIndex, CL_COL_START).setNumberFormat('@');
  sheet.getRange(rowIndex, CL_COL_END).setNumberFormat('@');
  sheet.getRange(rowIndex, 1, 1, 12).setValues([[
    videoUrl, videoTitle, clipTitle,
    start, end, 'pending',
    '', '', new Date().toISOString(),
    summary || '', '', videoFileId || ''
  ]]);
  return rowIndex;
}

/**
 * Updates the status of a clip row.
 * @param {GoogleAppsScript.Spreadsheet.Sheet} sheet
 * @param {number} rowIndex
 * @param {string} status
 * @param {string} [driveLink]
 * @param {string} [driveFileId]
 * @param {string} [errorMsg]
 */
function updateClipStatus(sheet, rowIndex, status, driveLink, driveFileId, errorMsg) {
  sheet.getRange(rowIndex, CL_COL_STATUS).setValue(status);
  if (driveLink)   sheet.getRange(rowIndex, CL_COL_DRIVE_LINK).setValue(driveLink);
  if (driveFileId) sheet.getRange(rowIndex, CL_COL_DRIVE_FILE).setValue(driveFileId);
  if (errorMsg)    sheet.getRange(rowIndex, CL_COL_ERROR_MSG).setValue(errorMsg);
}

// ============================================================
// Read helpers
// ============================================================

/**
 * Returns all clip rows as an array of objects.
 * @param {GoogleAppsScript.Spreadsheet.Sheet} sheet
 * @returns {Array<Object>}
 */
function getAllClips(sheet) {
  var lastRow = sheet.getLastRow();
  if (lastRow < 2) return [];
  return sheet.getRange(2, 1, lastRow - 1, 12).getValues().map(function(row, i) {
    return {
      rowIndex:    i + 2,
      videoUrl:    String(row[CL_COL_VIDEO_URL      - 1] || ''),
      videoTitle:  String(row[CL_COL_VIDEO_TITLE    - 1] || ''),
      clipTitle:   String(row[CL_COL_CLIP_TITLE     - 1] || ''),
      start:       String(row[CL_COL_START          - 1] || ''),
      end:         String(row[CL_COL_END            - 1] || ''),
      status:      String(row[CL_COL_STATUS         - 1] || ''),
      driveLink:   String(row[CL_COL_DRIVE_LINK     - 1] || ''),
      driveFileId: String(row[CL_COL_DRIVE_FILE     - 1] || ''),
      createdAt:   String(row[CL_COL_CREATED_AT     - 1] || ''),
      summary:     String(row[CL_COL_SUMMARY        - 1] || ''),
      errorMsg:    String(row[CL_COL_ERROR_MSG      - 1] || ''),
      videoFileId: String(row[CL_COL_VIDEO_FILE_ID  - 1] || ''),
    };
  });
}

/**
 * Deletes a clip row by 1-based row index.
 * @param {GoogleAppsScript.Spreadsheet.Sheet} sheet
 * @param {number} rowIndex
 */
function deleteClipRow(sheet, rowIndex) {
  sheet.deleteRow(rowIndex);
}
